swagger: '2.0'
info:
  description: API permettant de gérer la base de données
  version: 1.1.0
  title: DAWAGSI Database API
  contact:
    name: GitHub
    url: https://github.com/SkydeFR/DAWAGSI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: database
  description: Base de données
- name: list
  description: Liste d'images
- name: editor
  description: Editeur
- name: image
  description: Image
- name: annotation
  description: Annotation
- name: relation
  description: Relation

# endpoints
paths:
  /database:
    get:
      tags:
        - database
      summary: Vérifie la connexion à la base de données
      operationId: checkDB
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: object
            
  /list/create:
    post:
      tags:
        - list
      summary: Crée une nouvelle liste
      operationId: createList
      produces:
      - application/json
      parameters:
      - in: query
        type: string
        name: name
        description: nom de la liste
        required: true
      - in: query
        type: string
        name: description
        description: description de la liste
        required: false
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /list/selectAll:
    get:
      tags:
        - list
      summary: Sélectionne toutes les listes
      operationId: selectAllList
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
  /list/{id}:
    get:
      tags:
        - list
      summary: Sélectionne une liste
      operationId: selectList
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la liste
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    put:
      tags:
        - list
      summary: Met à jour une liste
      operationId: updateList
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la liste
        required: true
      - in: query
        type: string
        name: name
        description: nom de la liste
        required: true
      - in: query
        type: string
        name: description
        description: description de la liste
        required: false
      responses:
        200:
          description: successful operation
          schema:
            type: object
    delete:
      tags:
        - list
      summary: Supprime une liste
      operationId: deleteList
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la liste
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
            
  /editor/create:
    post:
      tags:
        - editor
      summary: Crée un nouvel éditeur
      operationId: createEditor
      produces:
      - application/json
      parameters:
      - in: query
        type: string
        name: name
        description: nom de l'éditeur
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /editor/selectAll:
    get:
      tags:
        - editor
      summary: Sélectionne tous les éditeurs
      operationId: selectAllEditor
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /editor/{id}:
    get:
      tags:
        - editor
      summary: Sélectionne un éditeur
      operationId: selectEditor
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'éditeur
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    put:
      tags:
        - editor
      summary: Met à jour un éditeur
      operationId: updateEditor
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'éditeur
        required: true
      - in: query
        type: string
        name: name
        description: nom de l'éditeur
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    delete:
      tags:
        - editor
      summary: Supprime un éditeur
      operationId: deleteEditor
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'éditeur
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
            
  /image/create:
    post:
      tags:
        - image
      summary: Crée une nouvelle image
      operationId: createImage
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: list
        description: id de la liste comportant l'image
        required: true
      - in: query
        type: string
        name: originalName
        description: nom original du fichier image
        required: true
      - in: query
        type: string
        name: generatedName
        description: nom md5 du fichier image
        required: true
      - in: query
        type: integer
        format: int64
        name: editor
        description: id de l'éditeur lié à l'image
        required: false
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /image/selectAll:
    get:
      tags:
        - image
      summary: Sélectionne toutes les images d'une liste
      operationId: selectAllImage
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: list
        description: id de la liste
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
  /image/{id}:
    get:
      tags:
        - image
      summary: Sélectionne une image
      operationId: selectImage
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'image
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    put:
      tags:
        - image
      summary: Met à jour une image
      operationId: updateImage
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'image
        required: true
      - in: query
        type: integer
        format: int64
        name: list
        description: id de la liste comportant l'image
        required: true
      - in: query
        type: string
        name: originalName
        description: nom original du fichier image
        required: true
      - in: query
        type: string
        name: generatedName
        description: nom md5 du fichier image
        required: true
      - in: query
        type: integer
        format: int64
        name: editor
        description: id de l'éditeur lié à l'image
        required: false
      responses:
        200:
          description: successful operation
          schema:
            type: object
    delete:
      tags:
        - image
      summary: Supprime une image
      operationId: deleteImage
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'image
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
              
  /annotation/create:
    post:
      tags:
        - annotation
      summary: Crée une nouvelle annotation
      operationId: createAnnotation
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image comportant l'annotation
        required: true
      - in: query
        type: string
        name: tag
        description: tag de l'annotation
        required: true
      - in: query
        type: string
        name: x
        description: position x de l'annotation
        required: true
      - in: query
        type: string
        name: y
        description: position y de l'annotation
        required: true
      - in: query
        type: string
        name: width
        description: longueur de l'annotation
        required: true
      - in: query
        type: string
        name: height
        description: hauteur de l'annotation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /annotation/selectAll:
    get:
      tags:
        - annotation
      summary: Sélectionne toutes les annotations d'une image
      operationId: selectAllAnnotation
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
  /annotation/find:
    get:
      tags:
        - annotation
      summary: Cherche une annotation en fonction de sa position sur une image
      operationId: findAnnotation
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image comportant l'annotation
        required: true
      - in: query
        type: string
        name: x
        description: position x de l'annotation
        required: true
      - in: query
        type: string
        name: y
        description: position y de l'annotation
        required: true
      - in: query
        type: string
        name: width
        description: longueur de l'annotation
        required: true
      - in: query
        type: string
        name: height
        description: hauteur de l'annotation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
  /annotation/{id}:
    put:
      tags:
        - annotation
      summary: Met à jour une annotation
      operationId: updateAnnotation
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'annotation
        required: true
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image comportant l'annotation
        required: true
      - in: query
        type: string
        name: tag
        description: tag de l'annotation
        required: true
      - in: query
        type: string
        name: x
        description: position x de l'annotation
        required: true
      - in: query
        type: string
        name: y
        description: position y de l'annotation
        required: true
      - in: query
        type: string
        name: width
        description: longueur de l'annotation
        required: true
      - in: query
        type: string
        name: height
        description: hauteur de l'annotation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    delete:
      tags:
        - annotation
      summary: Supprime une annotation
      operationId: deleteAnnotation
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de l'annotation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
            
  /relation/create:
    post:
      tags:
        - relation
      summary: Crée une nouvelle relation
      operationId: createRelation
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image comportant la relation
        required: true
      - in: query
        type: string
        name: predicate
        description: prédicat de relation
        required: true
      - in: query
        type: integer
        format: int64
        name: annotation1
        description: id de la première annotation composant la relation
        required: true
      - in: query
        type: integer
        format: int64
        name: annotation2
        description: id de la seconde annotation composant la relation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /relation/selectAll:
    get:
      tags:
        - relation
      summary: Sélectionne toutes les relations d'une image
      operationId: selectAllRelation
      produces:
      - application/json
      parameters:
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: object
  /relation/{id}:
    get:
      tags:
        - relation
      summary: Sélectionne une relation
      operationId: selectRelation
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la relation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    put:
      tags:
        - relation
      summary: Met à jour une relation
      operationId: updateRelation
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la relation
        required: true
      - in: query
        type: integer
        format: int64
        name: image
        description: id de l'image comportant la relation
        required: true
      - in: query
        type: string
        name: predicate
        description: prédicat de relation
        required: true
      - in: query
        type: integer
        format: int64
        name: annotation1
        description: id de la première annotation composant la relation
        required: true
      - in: query
        type: integer
        format: int64
        name: annotation2
        description: id de la seconde annotation composant la relation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object
    delete:
      tags:
        - relation
      summary: Supprime une relation
      operationId: deleteRelation
      produces:
      - application/json
      parameters:
      - in: path
        type: integer
        format: int64
        name: id
        description: id de la relation
        required: true
      responses:
        200:
          description: successful operation
          schema:
            type: object

# definitions of common objects
definitions: {}

# host
host: skydefr.com
basePath: /ptut/api/slim
schemes:
 - http